name: Scheduled Workflow

on:
  schedule:
  - cron: '0/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python find-room-in-london.py myrooms
        python find-room-in-london.py spareroom
    - name: Artifact Spareroom.csv
      uses: actions/upload-artifact@master
      with:
        name: spareroom-rooms.csv
        path: ./spareroom.csv
    - name: Artifact Myrooms.csv
      uses: actions/upload-artifact@master
      with:
        name: myrooms-rooms.csv
        path: ./myrooms.csv
    - name: Push to master
      run: |
        git add .
        git commit -m "Update"
        git push origin master