name: Scheduled Workflow

on:
  schedule:
  - cron: '25 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python find-room-in-london.py myrooms
        python find-room-in-london.py spareroom
    - name: Publish files
      run: |
        git config --global user.name "${{ secrets.username }}"
        git config --global user.email "${{ secrets.email }}"
        git add .
        git ci -m "Update rooms"
        git push origin master